# Generated by Django 3.2.8 on 2021-10-17 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anken',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='No.')),
                ('anken_id', models.IntegerField(verbose_name='案件番号')),
                ('item_name', models.CharField(max_length=20, verbose_name='件名')),
                ('ope_name', models.CharField(max_length=20, verbose_name='担当者')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 17, 21, 11, 58, 56430), verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 10, 17, 21, 11, 58, 56447), verbose_name='更新日時')),
                ('inq_type', models.CharField(choices=[('Inquiry', '見積'), ('Order', '注文')], default='見積', max_length=10, verbose_name='種類')),
                ('progress', models.CharField(choices=[('InqNow', '見積中'), ('InqDone', '見積完了'), ('PartDone', '一部完了'), ('AllDone', '全部完了')], default='見積中', max_length=10, verbose_name='進捗')),
                ('body_num', models.CharField(default='0000', max_length=10, verbose_name='車台番号')),
            ],
        ),
    ]
