# Generated by Django 3.2.8 on 2021-10-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anken',
            fields=[
                ('ankenid', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
                ('ope_name', models.CharField(max_length=20)),
            ],
        ),
    ]
