# Generated by Django 3.2.8 on 2021-10-16 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 0, 22, 20, 714697), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 0, 22, 20, 714712), verbose_name='更新日時'),
        ),
    ]
