# Generated by Django 3.2.8 on 2021-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anken',
            name='ankenid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='案件番号'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='item_name',
            field=models.CharField(max_length=20, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='ope_name',
            field=models.CharField(max_length=20, verbose_name='担当者'),
        ),
    ]
