# Generated by Django 3.2.8 on 2021-10-16 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anken', '0006_auto_20211017_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 1, 37, 26, 159681), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 1, 37, 26, 159697), verbose_name='更新日時'),
        ),
    ]
